use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn preset_id(path: &Path) -> String {
    let id = path
        .file_stem()
        .and_then(|value| value.to_str())
        .expect("preset asset names must be valid UTF-8");

    if id.is_empty()
        || !id.chars().all(|character| {
            character.is_ascii_lowercase()
                || character.is_ascii_digit()
                || character == '_'
                || character == '-'
        })
    {
        panic!("invalid preset asset id \"{id}\": use lowercase letters, digits, '_' or '-'");
    }

    id.to_string()
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let preset_dir = manifest_dir.join("assets/presets");
    let mut presets: Vec<(String, PathBuf)> = fs::read_dir(&preset_dir)
        .expect("embedded preset directory must exist")
        .filter_map(|entry| {
            let path = entry
                .expect("preset directory entry must be readable")
                .path();
            (path.extension().and_then(|value| value.to_str()) == Some("json"))
                .then(|| (preset_id(&path), path))
        })
        .collect();

    presets.sort_by(|left, right| left.0.cmp(&right.0));
    if presets.is_empty() {
        panic!("at least one embedded preset JSON asset is required");
    }

    let entries = presets
        .iter()
        .map(|(id, path)| {
            let path = path
                .strip_prefix(&manifest_dir)
                .expect("preset asset must live under CARGO_MANIFEST_DIR")
                .to_string_lossy()
                .replace('\\', "/");
            format!(
                "    EmbeddedPreset {{\n        id: \"{id}\",\n        json: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{path}\")),\n        profile: OnceLock::new(),\n    }},"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let generated = format!(
        "// Generated by build.rs from assets/presets/*.json.\n\
         static EMBEDDED_PRESETS: [EmbeddedPreset; {}] = [\n{entries}\n];\n",
        presets.len()
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set"));
    fs::write(out_dir.join("embedded_presets.rs"), generated)
        .expect("generated embedded preset registry must be writable");

    println!("cargo:rerun-if-changed={}", preset_dir.display());
}
